name: 'Build container and deploy to GHCR'

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Check if Git tag exists"
        id: get_git_tag
        run: |
          echo "VERSION=$(git tag --points-at HEAD)" >> $GITHUB_ENV
      - name: "Set Docker metadata"
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/jc0b/discordbot
          # generate Docker tags based on the following events/attributes
          tags: |
            latest
            ${{ env.VERSION }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: python/
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
        if:
          env.VERSION != ''